# The prefix given to your bedrock players, you can find this in Floodgate's config. (Default: ".")
floodgatePrefix: "."
# How often to update bedrock player locations in ms.
# Lower values mean less rubber banding, but are more CPU intensive.
locationUpdateInterval: 1000
